version: '2'
services:
  telegraph:
    image: telegraf:alpine
    container_name: telegraf
    network_mode: "host"
#    ports:
#     - "8125:8125/udp"
    volumes:
     - /etc/telegraf:/etc/telegraf
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    network_mode: "host"
#    ports:
#     - "8086:8086"
#     - "8083:8083"
    volumes:
     - /etc/influxdb:/etc/influxdb
    command: -config /etc/influxdb/influxdb.conf 
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "host"
#    ports:
#     - "3000:3000"
  kapacitor:
    image: kapacitor:alpine
    container_name: kapacitor
    network_mode: "host"
#    ports:
#     - "9092:9092"
    volumes:
     - /etc/kapacitor:/etc/kapacitor
     - /tmp/kapacitor:/tmp 
