version: '2'
services:
  telegraph:
    image: telegraf:alpine
    container_name: telegraf
    ports:
     - "8125:8125/udp"
    volumes:
     - /etc/telegraf:/etc/telegraf
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
     - "8086:8086"
     - "8083:8083"
    volumes:
     - /etc/influxdb:/etc/influxdb
    command: -config /etc/influxdb/influxdb.conf 
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - "3000:3000" 
